# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

u1 = User.create(username: "mike", password: "testing", fp_url: 'https://www.filepicker.io/api/file/fbcdO6dKSCGPimifqhRW')
u2 = User.create(username: "jimmy", password: "testing", fp_url: 'https://www.filepicker.io/api/file/FXuj2BpqTX6J7iLr4Gr4')
u3 = User.create(username: "eric", password: "testing")
u4 = User.create(username: "rob", password: "testing")
u5 = User.create(username: "yusuf", password: "testing")
u6 = User.create(username: "guest", password: "welcome")
u7 = User.create(username: "ned", password: "testing")
u8 = User.create(username: "will", password: "testing")
u9 = User.create(username: "jeff", password: "testing")
u10 = User.create(username: "cj", password: "testing")
u11 = User.create(username: "shawna", password: "testing")

b1 = Business.create(name: "Saigon Sandwich", b_type: "Restaurants", price: 1, x_coord: 37.783146, y_coord: -122.417381)
b2 = Business.create(name: "Philz Coffee", b_type: "Coffee & Tea", price: 2, x_coord: 37.781332, y_coord: -122.416737)
b3 = Business.create(name: "Tropisueno", b_type: "Restaurants", price: 3, x_coord: 37.785394, y_coord: -122.403967)
b4 = Business.create(name: "Elbo Room", b_type: "Bars & Nightlife", price: 2, x_coord: 37.762515, y_coord: -122.421513)
b5 = Business.create(name: "Showdogs", b_type: "Restaurants", price: 2, x_coord: 37.782118, y_coord: -122.410881)
b6 = Business.create(name: "Tempest", b_type: "Bars & Nightlife", price: 2, x_coord: 37.781168, y_coord: -122.406289)
b7 = Business.create(name: "In-N-Out", b_type: "Restaurants", price: 1)
b8 = Business.create(name: "Giant Monkey Movers", b_type: "Home Services", price: 4)
b9 = Business.create(name: "Friendly Plumber", b_type: "Home Services", price: 1)
b10 = Business.create(name: "Happy Donuts", b_type: "Bakeries", price: 1)
b11 = Business.create(name: "Little Sheep Hot Pot", b_type: "Restaurants", price: 3)
b12 = Business.create(name: "Batter Bakery", b_type: "Bakeries", price: 1)
b13 = Business.create(name: "Noc Noc", b_type: "Bars & Nightlife", price: 2, x_coord: 37.771849, y_coord: -122.4314)
b14 = Business.create(name: "Split Bread", b_type: "Restaurants", price: 2, x_coord: 37.784118, y_coord: -122.403561)
b15 = Business.create(name: "SFMOMA", b_type: "Arts & Entertainment", price: 1)
b16 = Business.create(name: "Oolong Noodles Restaurant", b_type: "Restaurants", price: 3)
b17 = Business.create(name: "Señor Sisig", b_type: "Food Carts", price: 1)
b18 = Business.create(name: "Blue Cross Pet Hospital", b_type: "Health & Medical", price: 1, x_coord: 37.779627, y_coord: -122.433349)
b19 = Business.create(name: "Tu Lan Vietnamese Restaurant", b_type: "Restaurants", price: 1, x_coord: 37.781861, y_coord: -122.410144)
b20 = Business.create(name: "Brenda's", b_type: "Restaurants", price: 2, x_coord: 37.78292, y_coord: -122.418971)
b21 = Business.create(name: "Yerba Buena Gardens", b_type: "Arts and Entertainment", price: 1, x_coord: 37.785094, y_coord: -122.40274)
b22 = Business.create(name: "Westfield San Francisco Centre", b_type: "Shopping", price: 2, x_coord: 37.784143, y_coord: -122.407361)

r1 = Review.create(content: "this place is da bomb", stars: 5, user_id: 1, business_id: 1, go_again: true)
r2 = Review.create(content: "i think someone spit in my food", stars: 1, user_id: 3, business_id: 1, go_again: true)
	r2.toggle!(:go_again)
r3 = Review.create(content: "i feel neutral about this experience", stars: 3, user_id: 4, business_id: 1, go_again: true)
r4 = Review.create(content: "eh...", stars: 2, user_id: 5, business_id: 1, go_again: true)
	r4.toggle!(:go_again)
r5 = Review.create(content: "mmmm coffee. gettin mah fix", stars: 5, user_id: 3, business_id: 2, go_again: true)
r6 = Review.create(content: "everything is okay when i drink", stars: 4, user_id: 1, business_id: 4, go_again: true)
r7 = Review.create(content: "these guys were pretty good. i felt like the price was fair and they were done quickly.", stars: 4, user_id: 1, business_id: 9, go_again: true)
r8 = Review.create(content: "i think i got food poisoning from the soup", stars: 1, user_id: 7, business_id: 16, go_again: true)
	r8.toggle!(:go_again)
r9 = Review.create(content: "okay. very good.", stars: 4, user_id: 7, business_id: 13, go_again: true)
r10 = Review.create(content: "the sandwiches are tasty, and the price is good. my favorite is the pork.", stars: 5, user_id: 11, business_id: 1, go_again: true)
r11 = Review.create(content: "everyone should go here at least once - it's so tasty", stars: 4, user_id: 9, business_id: 1, go_again: true)
r12 = Review.create(content: "too crowded, the beer was only average", stars: 2, user_id: 10, business_id: 13, go_again: true)
	r12.toggle!(:go_again)
r13 = Review.create(content: "i like art", stars: 4, user_id: 1, business_id: 15, go_again: true)
r14 = Review.create(content: "oh yes, burrito", stars: 4, user_id: 10, business_id: 3, go_again: true)
r15 = Review.create(content: "fajitas all day", stars: 4, user_id: 11, business_id: 3, go_again: true)
r16 = Review.create(content: "i like margaritas", stars: 5, user_id: 5, business_id: 3, go_again: true)
r17 = Review.create(content: "okay. very very good.", stars: 5, user_id: 1, business_id: 17, go_again: true)
r18 = Review.create(content: "they close too early", stars: 1, user_id: 7, business_id: 19, go_again: true)
	r18.toggle!(:go_again)
r19 = Review.create(content: "i like it animal style", stars: 4, user_id: 1, business_id: 7, go_again: true)
r20 = Review.create(content: "i like it animal style", stars: 4, user_id: 1, business_id: 18, go_again: true)
r21 = Review.create(content: "combo platter!!!", stars: 5, user_id: 3, business_id: 11, go_again: true)
r22 = Review.create(content: "spicy broth is win", stars: 4, user_id: 4, business_id: 11, go_again: true)
r23 = Review.create(content: "booooooooring", stars: 2, user_id: 11, business_id: 15, go_again: true)
	r23.toggle!(:go_again)
r24 = Review.create(content: "ah yes, great times", stars: 4, user_id: 2, business_id: 14, go_again: true)
r25 = Review.create(content: "oh no, bad times", stars: 2, user_id: 2, business_id: 19, go_again: true)
	r25.toggle!(:go_again)
r26 = Review.create(content: "hunger is over", stars: 5, user_id: 9, business_id: 17, go_again: true)
r27 = Review.create(content: "i believe this is the best bakery of all time", stars: 5, user_id: 9, business_id: 12, go_again: true)